Repository lidofinance/lido-oracle, pull requests merged in 2020-12, with the labels that each got.

#50 Supervised (interactive) mode with TX confirmation
  .github/workflows/linters.yml
  README.md
  app/oracle.py
  docker-compose.yml
  run_tests.sh
  tests/patch
  tests/test_oracle.py
Labels: enhancement

#58 Non-waiting algorithm #53
  app/beacon.py
  app/oracle.py
  helpers/__init__.py
  requirements-test.txt
Labels: enhancement

#60 version bumber #55
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  app/oracle.py
  build.sh
  build_and_push.sh
  helpers/get_git_info.py
  tests/test_get_semver_tag.py
  tests/test_log_version_on_oracle_start.py
Labels: enhancement, infrastructure

#90 Unit tests for APR-related metric indications #89
  tests/test_pool_metrics.py
Labels: qa
